### PR TITLE
Use vscode's URI implementation, for better compatibility.

### PR DESCRIPTION
**Pull request by rictic**
- [x] CHANGELOG.md not updated. This is a minor stability patch with nothing user visible, though it may fix some unknown issues with unusual file names.

### CODE REVIEW

**Comment by usergenic** [comment]
Looking at the build failures on travis it appears to be a double type-registration related thing because the specific installed linter includes a different version of analyzer...

**Comment by usergenic** [comment]
(I reran them fwiw)

**Comment by usergenic** [comment]
Looks like maybe that goes away in https://github.com/Polymer/polymer-editor-service/pull/52

**Comment by rictic** [comment]
Yeah, we have a ^ on the linter version, but we need the same analyzer version in the editor service and the linter...

We really just need to publish a real version of the analyzer. Until then, we'll get this kind of weirdness.

**Pull request merged**
