### PR TITLE
Support the `polymer-ide.analyzeWholePackage` setting.

### PR DESCRIPTION
**Pull request by rictic**
- [x] CHANGELOG.md has been updated

---
This change is [Reviewable](https://reviewable.io/reviews/polymer/polymer-editor-service/63)

### CODE REVIEW

**Comment by aomarks** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/polymer/polymer-editor-service/63#-KhODi8vwoK3nXoCmna_:-KhODi8vwoK3nXoCmnaa:b-vmx8so) (no related file):*
Is there any easy way to unit test this?

---

*[src/editor-service.ts, line 95 at r1](https://reviewable.io:443/reviews/polymer/polymer-editor-service/63#-KhOCt5mHbFbsYfTmTz6:-KhOCt5mHbFbsYfTmTz7:by8lm2n) ([raw file](https://github.com/polymer/polymer-editor-service/blob/706e1c39809eef3e9ca30da9065d070aa606c377/src/editor-service.ts#L95)):*
> ```XML
>   abstract async getWarningsForFile(localPath: string): Promise<Warning[]>;
> 
>   abstract async getWarningsForPackage(): Promise<Warning[]>;
> ```

Document?

---

*[src/remote-editor-service.ts, line 127 at r1](https://reviewable.io:443/reviews/polymer/polymer-editor-service/63#-KhOD813Qr7v4ykLDBGJ:-KhOD813Qr7v4ykLDBGK:buqs8rs) ([raw file](https://github.com/polymer/polymer-editor-service/blob/706e1c39809eef3e9ca30da9065d070aa606c377/src/remote-editor-service.ts#L127)):*
> ```XML
>     return this._channel.request({kind: 'getWarningsForPackage'});
>   }
> ```

Nit: extra newline here.

---

*[src/language-server/language-server.ts, line 46 at r1](https://reviewable.io:443/reviews/polymer/polymer-editor-service/63#-KhODC0SQzVHCB9S2AJv:-KhODC0SQzVHCB9S2AJw:bkgi15k) ([raw file](https://github.com/polymer/polymer-editor-service/blob/706e1c39809eef3e9ca30da9065d070aa606c377/src/language-server/language-server.ts#L46)):*
> ```XML
>   analyzeWholePackage: boolean;
> }
> const defaultSettings: Readonly<Settings> =
> ```

Do we use CONST_CASE?

---

*[src/language-server/language-server.ts, line 169 at r1](https://reviewable.io:443/reviews/polymer/polymer-editor-service/63#-KhODGs8vWyYXkhIxOSo:-KhODGs8vWyYXkhIxOSp:b-ta7x7h) ([raw file](https://github.com/polymer/polymer-editor-service/blob/706e1c39809eef3e9ca30da9065d070aa606c377/src/language-server/language-server.ts#L169)):*
> ```XML
> 
>     this._connection.onDidChangeConfiguration((change) => {
>       console.log(change.settings);
> ```

Remove log statement?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/polymer/polymer-editor-service/63)*

**Comment by rictic** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/polymer/polymer-editor-service/63#-KhODi8vwoK3nXoCmna_:-KhOEvr5A_uaZTH0-TjQ:b41mvsq) (no related file):*
<details><summary><i>Previously, aomarks (Alexander Marks) wrote…</i></summary><blockquote>

Is there any easy way to unit test this?
</blockquote></details>

Annoyingly, it's trickier than it looks. I have a WIP branch but using the vscode's LSP client has some issues, as it wants to use the `vscode` npm module, but that can only be imported in some contexts? Still investigating.

---

*[src/editor-service.ts, line 95 at r1](https://reviewable.io:443/reviews/polymer/polymer-editor-service/63#-KhOCt5mHbFbsYfTmTz6:-KhOvxDJ8Yzc-Cx7-DNn:b-896fix) ([raw file](https://github.com/polymer/polymer-editor-service/blob/706e1c39809eef3e9ca30da9065d070aa606c377/src/editor-service.ts#L95)):*
<details><summary><i>Previously, aomarks (Alexander Marks) wrote…</i></summary><blockquote>

Document?
</blockquote></details>

Done.

---

*[src/remote-editor-service.ts, line 127 at r1](https://reviewable.io:443/reviews/polymer/polymer-editor-service/63#-KhOD813Qr7v4ykLDBGJ:-KhOw1FXWO0JSzh3Tx3u:b-896fix) ([raw file](https://github.com/polymer/polymer-editor-service/blob/706e1c39809eef3e9ca30da9065d070aa606c377/src/remote-editor-service.ts#L127)):*
<details><summary><i>Previously, aomarks (Alexander Marks) wrote…</i></summary><blockquote>

Nit: extra newline here.
</blockquote></details>

Done.

---

*[src/language-server/language-server.ts, line 46 at r1](https://reviewable.io:443/reviews/polymer/polymer-editor-service/63#-KhODC0SQzVHCB9S2AJv:-KhOFT5EaKkp25TRd53z:b-ttbol9) ([raw file](https://github.com/polymer/polymer-editor-service/blob/706e1c39809eef3e9ca30da9065d070aa606c377/src/language-server/language-server.ts#L46)):*
<details><summary><i>Previously, aomarks (Alexander Marks) wrote…</i></summary><blockquote>

Do we use CONST_CASE?
</blockquote></details>

We do not.

---

*[src/language-server/language-server.ts, line 169 at r1](https://reviewable.io:443/reviews/polymer/polymer-editor-service/63#-KhODGs8vWyYXkhIxOSo:-KhOw6IWXlAr4QI4Zvi_:b4g0byb) ([raw file](https://github.com/polymer/polymer-editor-service/blob/706e1c39809eef3e9ca30da9065d070aa606c377/src/language-server/language-server.ts#L169)):*
<details><summary><i>Previously, aomarks (Alexander Marks) wrote…</i></summary><blockquote>

Remove log statement?
</blockquote></details>

oops, done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/polymer/polymer-editor-service/63)*

**Comment by aomarks** [comment]
Reviewed 2 of 7 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/polymer/polymer-editor-service/63)*

**Comment by aomarks** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/polymer/polymer-editor-service/63#-:-KhOxgmPZalpZwJfDo9i:bnfp4nl)*

**Pull request merged**
